REVOKE ALL PRIVILEGES ON SCHEMA innergerbil FROM gerbil;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA innergerbil FROM gerbil;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA innergerbil FROM gerbil;
DROP USER gerbil;

DROP TABLE IF EXISTS "contactdetails" CASCADE;

DROP TABLE IF EXISTS "parties" CASCADE;
DROP TABLE IF EXISTS "partycontactdetails" CASCADE;

DROP TABLE IF EXISTS "relations" CASCADE;

DROP TABLE IF EXISTS "transactions" CASCADE;
DROP TABLE IF EXISTS "transactionrelations" CASCADE;

DROP TABLE IF EXISTS "messages" CASCADE;
DROP TABLE IF EXISTS "messagecontactdetails" CASCADE;
DROP TABLE IF EXISTS "messagetags" CASCADE;
DROP TABLE IF EXISTS "messageparties" CASCADE;
DROP TABLE IF EXISTS "messagephotos" CASCADE;
DROP TABLE IF EXISTS "messagetransactions" CASCADE;

DROP SCHEMA IF EXISTS innergerbil CASCADE;
