REVOKE ALL PRIVILEGES ON SCHEMA innergerbil FROM gerbil;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA innergerbil FROM gerbil;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA innergerbil FROM gerbil;
DROP USER gerbil;

DROP SCHEMA IF EXISTS innergerbil CASCADE;
